[package]
name = "btc"
version = "0.1.0"
authors = ["James Mountain <31282623+jmountain-hmrc@users.noreply.github.com>"]
edition = "2018"

[dependencies]
reqwest = "0.9.12"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.39"
mongodb = "0.3.12"